management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
info:
  env:
    enabled: true

spring:
  data:
    zipkin:
      baseUrl: http://zipkin:9411/
      enabled: true
      sender:
        type: rabbit
#eureka:
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#      Instance:
#        preferIpAddress: true