server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: http://catalog-service:8081/
          predicates:
            - Path=/movies/**
            - Path=/series/**
            - Path=/catalog/**
#        - id: games
#          uri: http://localhost:8081
#          predicates:
#            - Path=/catalog/**
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true