server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seriesdb

  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq
    port: 5672

queue:
  catalog:
    name: catalogQueue

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka